### ISSUE TITLE
Segfault when running on default region

### ISSUE THREAD

**Issue by sbkg0002** [adamcrosby/aws-cis-scanner#8]
Hi,

When running v1.1 on Ubuntu 16.04, it segfaults with the following error:
```
./aws-cis-scanner-linux-x64-v1.1
BucketRegionError: incorrect region, the bucket is not in 'ap-northeast-1' region
	status code: 301, request id:
BucketRegionError: incorrect region, the bucket is not in 'ap-northeast-1' region
	status code: 301, request id:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x491419]

goroutine 1 [running]:
panic(0x9c4bc0, 0xc42000a0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/adamcrosby/aws-cis-scanner/benchmark.s3BucketPolicyChecks(0xc4200240b0, 0xc420443420, 0x1b, 0xaacf01)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/benchmark/logging.go:203 +0x139
github.com/adamcrosby/aws-cis-scanner/benchmark.ensureS3LogsBucketNotPublic(0xc42043da70, 0x2, 0x2, 0xc4200240b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/benchmark/logging.go:152 +0x17e
github.com/adamcrosby/aws-cis-scanner/benchmark.LoggingChecks(0xc4200240d0, 0xc4200240c0, 0xc4200240b0, 0xc4200240a0, 0xc4200119b0, 0xc420024110)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/benchmark/logging.go:52 +0x2b5
main.checkRegion(0xc4200119b0, 0xc420070c60, 0x0, 0x0, 0x0, 0xc42000bbd0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/aws-cis-scanner.go:99 +0x4f3
main.main()
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/aws-cis-scanner.go:61 +0x2b9
```

When running with `-r "eu-west-1"`, it completes within a second, without checking anything:
```
real	0m0.013s
user	0m0.008s
sys	0m0.004s
```

Suggestion on how to fix this? This tools surely looks nice!

**Comment by adamcrosby** [comment]
Thanks for the bug report.
It exits immediately with `-r eu-west-1` due to a logic flaw - I started implementing single region scans, but apparently never finished, so if you specify a region that's not GovCloud or Beijing, it just skips all regions.  If you *don't* specify a region, it will scan all commercial regions, currently defined as:
```go
var CommercialRegions = []string{APNorthEast1, APNorthEast2, APSouth1, APSouthEast1, APSouthEast2, EUCentral1, EUWest1, SAEast1, USEast1, USWest1, USWest2}
```
That's an easy fix.


For the `BucketRegionError`, things are slightly more complicated.  I'll need to look into that one a bit more - is your CloudTrail S3 bucket potentially not in the same Region as the scanner is running (i.e. do you log CloudTrail from, say, `us-east-1` to `ap-northeast-1`?  

I'm pretty sure I see the issue here (need to add bucket location checking to the query), but want to make sure that's what is actually blowing up for you.

**Comment by sbkg0002** [comment]
Thanks for the fast feedback. I will try to build a new version with the fix later. If it works, I'll create a PR.

As for the CloudTrail bucket: it is located in another account, within the same region.

**Comment by adamcrosby** [comment]
Does the account you're using to run the scan have permissions to read the Bucket Policy on the bucket you're logging to?
Either way, I need to add in some error checking, obviously.

**Comment by sbkg0002** [comment]
No, since I need to assume a role in another account for that.

**Comment by adamcrosby** [comment]
Ah!  OK.  Hmmm, to support that, we'd need to facilitate some configuration beyond the basic SDK supported config ('credentials file' type stuff) to let you designate a roll to assume for specific checks. 
I'm going to need to think about how to best approach that, unless you have an idea?

I'll add in some error checking regardless of solution, so it shouldn't segfault, but rather indicate the error.

**Comment by sbkg0002** [comment]
My Go knowledge is very minimal, so no technical suggestions unfortunately.
Since this might be the case for more people, maybe a flag to specify the
role arn to be used for CloudTrail buckets?

**Comment by adamcrosby** [comment]
I guess it's not a 'go' issue, so much as 'what would you like to see from an interface perspective' issue.  A config file? a command line argument?

**Comment by sbkg0002** [comment]
Since it's only the second option (after region), I'd make it a flag.

Op 7 apr. 2017 15:58 schreef "Adam Crosby" <notifications@github.com>:

**Comment by adamcrosby** [comment]
OK, v1.2 bin's are uploaded.  It no longer ignores the -r flag :)
Still working on error handling around the s3 bucket access, etc., and the ARN config.

**Comment by sbkg0002** [comment]
Super! Will test tomorrow morning.

Edit: Specifying the region to `eu-west-1` now works, thanks @adamcrosby! 

Is there a way to skip the CloudTrail check for now?

Op 9 apr. 2017 18:06 schreef "Adam Crosby" <notifications@github.com>:

**Comment by adamcrosby** [comment]
Just wanted to update: I think I've got this figured out (STS in the go sdk is a pain), and should have a branch pushed up in a bit with a fix for you to test.

**Comment by adamcrosby** [comment]
Hi @sbkg0002 can you pull a binary from the `sts` branch and check now?
https://github.com/adamcrosby/aws-cis-scanner/tree/sts/bin

Pass in `-arn <remote role arn> -extid <extid>` for your STS role assumption.  If your role doesn't require an extid, just leave that flag off.

```
$ aws-cis-scanner -arn arn:aws:iam::1234456789:role/STSAuditorRole -extid 11111 > report.html
```
or
```
$ aws-cis-scanner -arn arn:aws:iam::1234456789:role/STSAuditorRole  > report.html
```

The '-r' region flags should still work as well.

Thanks!

**Comment by sbkg0002** [comment]
@adamcrosby unfortunately, it didn't work:
```
$ ./aws-cis-scanner-linux-x64-v1.3 -arn arn:aws:iam::12345678:role/role-admin -r eu-west-1 > report.html
panic: AccessDenied: User: arn:aws:sts::12345678:assumed-role/instance-role-with-assume/i-036118a868d9ca is not authorized to perform: iam:GenerateCredentialReport
	status code: 403, request id: 1c5d64a3-33fb-11e7-8ea7-91a3e9add6ea

goroutine 1 [running]:
github.com/adamcrosby/aws-cis-scanner/utility/accounts.getAccountInformation(0xc42000c0c0)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/utility/accounts/accounts.go:30 +0x1d9
github.com/adamcrosby/aws-cis-scanner/utility/accounts.getDecodedCredentialReport(0xc42000c0c0, 0x2, 0x0, 0x3)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/utility/accounts/accounts.go:53 +0x40
github.com/adamcrosby/aws-cis-scanner/utility/accounts.GetAccounts(0xc42000c0c0, 0x0, 0x9, 0xd1ce11)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/utility/accounts/accounts.go:93 +0x2b
github.com/adamcrosby/aws-cis-scanner/benchmark.DoIAMChecks(0xc42000c0c0, 0xc42000c0d8, 0xc42000c0f0, 0xc42000c1a8, 0xc42000c108, 0xc42000c120, 0xc42000c138, 0xc42000c150, 0xc42000c168, 0xc42000c180, ...)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/benchmark/iamchecks.go:28 +0x43
main.checkRegion(0xc42010fa40, 0xc42000c0c0, 0xc42000c0d8, 0xc42000c0f0, 0xc42000c1a8, 0xc42000c108, 0xc42000c120, 0xc42000c138, 0xc42000c150, 0xc42000c168, ...)
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/aws-cis-scanner.go:126 +0x4b
main.main()
	/Users/adam/code/golang/src/github.com/adamcrosby/aws-cis-scanner/aws-cis-scanner.go:91 +0x8d2
```
Any idea?

**Comment by adamcrosby** [comment]
Sorry, I don't know how this fell thru the cracks.  It appears your user doesn't have the right permissions (`iam:GenerateCredentialReport` is required).
